# Generated by Django 5.2.12 on 2026-03-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('avatar', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('availability', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('hoursPerWeek', models.IntegerField()),
                ('hoursAllocated', models.IntegerField()),
                ('hoursAvailable', models.IntegerField()),
                ('tasksCompleted', models.IntegerField()),
                ('tasksInProgress', models.IntegerField()),
                ('avgCompletionTime', models.FloatField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
