# Generated by Django 5.2.12 on 2026-03-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='currentProjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resource',
            name='qualifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resource',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resource',
            name='weeklyAvailability',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resource',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('partial', 'Partially Available'), ('busy', 'Busy')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='avatar',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='avgCompletionTime',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='hoursAllocated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='hoursAvailable',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='hoursPerWeek',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='resource',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tasksCompleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tasksInProgress',
            field=models.IntegerField(default=0),
        ),
    ]
