# Generated by Django 5.2.12 on 2026-03-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('project', models.CharField(max_length=100)),
                ('assignee', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('overdue', 'Overdue'), ('due_soon', 'Due Soon')], default='due_soon', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('on_track', 'On Track'), ('complete', 'Complete')], default='in_progress', max_length=20)),
            ],
        ),
    ]
