# Generated by Django 5.2.12 on 2026-03-26 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='todo', max_length=20)),
                ('estimated_days', models.PositiveIntegerField(default=0)),
                ('estimated_hours', models.PositiveIntegerField(default=0)),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('person_responsible', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ai_tools.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
