# Generated by Django 5.2.13 on 2026-04-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0003_task_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
