services:
  - type: web
    name: django-soft-dash-release
    plan: starter
    env: python
    region: frankfurt  # region should be same as your database region.
    buildCommand: "./deployment/build.sh"
    startCommand: "gunicorn --chdir backend --config backend/gunicorn-cfg.py config.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
