# Generated by Django 5.2.12 on 2026-04-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soapprojecttransaction',
            name='operation',
            field=models.CharField(choices=[('create', 'Create'), ('modify', 'Modify')], default='create', max_length=20),
        ),
    ]
